### ISSUE TITLE
FOLD RELIEF

### ISSUE THREAD

**Issue by JereSalo** [Chabelamas/Haskell#1]
**Si está buscando un especialista que trate su foldadicción llame ya al 0800-196-FOLD y conseguirá un descuento del ((length.nombre) persona)% en nuestro paquete anti-fold, que incluye la más nueva tecnología Fold Relief, en el que lo obligaremos de por vida a hacer todo con recursividad !**

_0800-196-FOLD_
¿Qué espera? **LLAME YA!**

**Comment by Chabelamas** [comment]
Buenos días! Agradezco la oferta, cuanto saldría el paquete anti-fold?

**Comment by JereSalo** [comment]
> Buenos días! Agradezco la oferta, cuanto saldría el paquete anti-fold?

PAQUETE ANTI-FOLD A TAN SOLO 
`foldl (\llame ya -> llame `div` 6 + 100 * ya - 171) 5 [0,8,0,0,1,9,6,3,6,5,3]` lambdaCoins !!!



Pero si evaluó el fold significa que usted se encuentra enferma de verdad, así que tendrá un valor de **0 lambdaCoins** y el paquete Foldamigos **GRATIS**. Donde se le asignarán _sin su consentimiento_ amigos que se asegurarán de que el fold no forme nunca más parte de su vida y que de una vez por todas, sea _feliz_.

_0800-196-FOLD_
